development:
  adapter: postgresql
  database: sky_dance_development
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: skydance
  pool: 5
  username: skydance
  password: skydance73
